eventbrite/conformity

conformity/fields/__init__.py, conformity/fields/geo.py, conformity/fields/meta.py, conformity/fields/net.py, conformity/tests/test_fields.py, conformity/tests/test_fields_net.py
This adds three IP address fields: `IPv4Address`, `IPv6Address`, and `IPAddress`. The latter will accept either v4 or v6 addresses.
As part of this (it uses Any), I have removed the incorrect use of pointers in Any - all the errors point to the same variable, not to different indexes inside it.
=> Add IP Address fields (and fix Any to not use pointers)

conformity/fields/__init__.py, conformity/fields/meta.py, conformity/tests/test_fields_meta.py
This is designed to primarily sit in an `All()` clause next to a type checker. It will swallow invalid-type errors/attribute errors and turn them into a normal Conformity error so that works well if the type one doesn't pass.
=> Add BooleanValidator

conformity/fields/structures.py, conformity/tests/test_fields.py
In some edge cases it was trying to use the Attribute object from `attrs` as the value of `optional_keys`.
=> Fix override attribute test for Dictionary

.gitignore, conformity/fields/basic.py, conformity/tests/test_fields.py, conformity/tests/test_fields_meta.py
Since a lot of Any use was with constants, and the error messages were
long and a bit confusing, this gives the Constant field the ability to
have a set of options natively as multiple positional arguments to the
constructor. It's backwards compatible with the old calling style and
error messages, though the introspection format has changed.
=> Allowed Constant to take multiple options for a more concise Any+Const

.gitignore, .travis.yml, conformity/__init__.py, conformity/error.py, conformity/fields/__init__.py, conformity/fields/basic.py, conformity/fields/geo.py, conformity/fields/meta.py, conformity/fields/net.py, conformity/fields/structures.py, conformity/fields/temporal.py, conformity/tests/test_fields.py, conformity/tests/test_fields_geo.py, conformity/tests/test_fields_meta.py, conformity/tests/test_fields_net.py, conformity/tests/test_validator.py, conformity/validator.py, conformity/version.py, setup.cfg, setup.py
- Bump `attrs` from ~16.3 to ~17.4
- Clean up imports to follow our import style
- Add PyTest and code coverage calculation
=> Bump attrs, clean up imports, and add PyTest and coverage

conformity/fields/basic.py, tests/test_fields.py
The `List` field has minimum length and maximum length arguments. However, the `UnicodeString` and `ByteString` fields only have maximum length arguments. This means that someone could pass in an empty string to satisfy a field the service writer intends to be required. Adding a `min_length` argument should solve this.
=> Add support for specifying minimum required string length

conformity/fields/meta.py, tests/test_fields_meta.py
Introspection for the new `Nullable` field was incorrectly squashing inner introspection to a Python dict string. This breaks introspection. With this change, `Nullable` introspection defers to the first positional argument, but adds a `"nullable": True` key to the returned dictionary. If the returned dictionary has no description, the `Nullable` description will be used (if set).
=> Fix: Nullable introspection incorrectly squashed all inner introspection

conformity/fields/structures.py, tests/test_fields.py
When the compiler inlines a `tuple` for the `in` comparison, a small `tuple` is considerably faster than the same values in a `set` or a `list` (though that advantage eventually disappears for large iterables). However, when the same values in a `set`, a `list`, and a `tuple` are passed to something as an argument, the speed advantage is clearly in the favor of `set` in all scenarios:
```
In [1]: s1 = {'a', 'b', 'c', 'd', 'e', 'f', 'g'}
In [2]: s2 = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
In [3]: s3 = ('a', 'b', 'c', 'd', 'e', 'f', 'g')
In [4]: %timeit 'd' in s1
42.5 ns ± 2.11 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [5]: %timeit 'd' in s2
78.7 ns ± 1.19 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [6]: %timeit 'd' in s3
85.3 ns ± 2.07 ns per loop …
```
=> [PATCH] Ensure optional_keys is a set, introspects to a list

conformity/fields/temporal.py, setup.py, tests/test_fields.py
- `type(value) == datetime.tzinfo` can never be `True`. All time zone objects inherit frcom `tzinfo`, and so would always fail this test.
- `type(value) == datetime.datetime` and `type(value) == datetime.date` fail when under a Freezegun context. This makes it impossible to freeze time in a test and then send that time to or return it from a Conformity-enforced routine. We need to be more flexible and allow those types, dynamically, without breaking on the fact that `datetime.datetime` extends `datetime.date` but should not be a valid `Date`.
=> [MINOR] Make temporal type support more flexible

README.rst, conformity/error.py, conformity/fields/basic.py, conformity/fields/meta.py, conformity/fields/structures.py, setup.py, tests/test_fields.py
To better support clients that interpret received error codes to display helpful messages to humans, this adds support for machine-readable error codes to field validation. When not explicitly provided, the default error code is `INVALID`, which is appropriate in most cases. Missing keys in structures are `MISSING`. Extra keys in structures, and values that don't match expected constants, are `UNKNOWN`.
=> [MINOR] Add support for machine-readable error codes

conformity/fields/structures.py, tests/test_fields.py
If we can extend a `Dictionary`, we can more easily have an overriding class or method define a schema that builds on the base schema, without having to redefine the entire schema or implement hacky solutions that copy the attributes of the base schema manually.
=> [MINOR] Add support for extending dictionaries to simplify similar schemas

conformity/fields/email.py, tests/test_fields_email.py
There were three bugs in the email field (and the fix is in parentheses):
- Unused `code` constructor parameter (deprecated)
- Unused `message` constructor parameter (deprecated)
- Error implicit pointers improperly became error codes when codes were added between messages and pointers (made them explicit pointers)
=> [MINOR] Fix three bugs in the email field

README.rst
I guessed `from conformity import ...` and had to read the code to find out it was `from conformity.fields ...`
=> Include import in readme example

conformity/fields/basic.py
If a field subclass uses Attrs (such as `attr.ib`), it must be decorated with `@attr.s`, otherwise the attributes in it aren't handled properly.
=> [PATCH] Field subclasses that use Attrs must use attr.s

.travis.yml, setup.py
This commit premits a newer Attrs version and confirms that it works by passing all tests. Additionally, all tests pass with PyTest 4.0.0, so no changes are needed to support that. Finally, it adds a Python 3.7 Travis build to confirm proper operation on Python 3.7.
=> [PATCH] Permit a newer Attrs version and confirm it works

conformity/fields/basic.py, conformity/fields/currency.py, conformity/fields/email.py, conformity/fields/meta.py, conformity/fields/net.py, conformity/fields/structures.py
Adds `introspect_type` attribute to all field types. This allows to query any field class for its type literal (all non-derived ones currently have the `type` hardcoded at the `introspect()` method).
The reasoning is that I'm building a small tool that uses Conformity and right now I would have to hardcode a mapping of type literals and their associated conformity.field classes. This way each field states the value, without affecting normal behaviour of introspect() etc.
Caveats:
- I replaced the `type_noun` field at `List` and `Set`, but only to be coherent with other places where `introspect_type` was used for the same meaning, so I might be wrong.
- This introduces the danger of somebody inheriting an existing field and forgetting to replace the `introspect_type` value, but IMHO …
=> [MINOR] Adds introspect_type attribute to all fields

conformity/fields/basic.py, conformity/fields/structures.py, conformity/fields/temporal.py, tests/test_fields.py
In dictionary validation, the order of the keys isn't important (and, indeed, can't be enforced when dealing with Msgpack, JSON, and others). However, the order that errors are presented (for display purposes) and the order the keys are defined (for documentation purposes) might be important. This enhancement makes the `Dictionary` field aware of ordered dictionary inputs, returns validation errors in that order, extends with that order kept in mind, and returns key ordering documentation with the field introspection.
Side note: This change also fixes a minor bug: Classes that inherit from `@attr.s`-decorated classes but don't define a constructor must also be decorated with `@attr.s` in order for IDE inspection to work properly.
=> [MINOR] Enhance Dictionary field to permit ordered key documentation

conformity/fields/country.py, tests/test_fields_country.py
Summary
- Fix: introspect() should return a `list` of 'values' instead of a `set`
- Fix: 'Not a valid country code' errors should not point to a non-existing pointer "value"
- Sort the list of valid codes returned by introspect()
=> Minor fixes to CountryCodeField

conformity/fields/email.py, tests/test_fields_email.py
STR:
Add the following test to `conformity/tests/test_fields_email.py` and run `pytest`:
```
def test_whitelisted_address_via_constructor(self):
whitelisted_domains = ['a-whitelisted-domain']
schema = EmailAddress(whitelist=whitelisted_domains)
self.assertEqual(
schema.errors('a-name@a-whitelisted-domain'),
[],
)
```
Fails although Email field's init has it: `def __init__(self, message=None, code=None, whitelist=None)`. 
Also the constructor looks weird, instead of having the interface/expected parameters of `EmailAddress` has those defined at  `UnicodeString` as `attr.ib`:
```
ipdb> conformity.fields.email.EmailAddress()
EmailAddress(min_length=None, max_length=None, description=None, allow_blank=True)
```
This happens because `whitelist` is not marked as an `attr.ib` so the …
=> Fix EmailAddress whitelist not working

.dockerignore, .gitignore, .travis.yml, Dockerfile, setup.cfg, setup.py, tox.ini, tox.sh
This commit does the following:
- Bumps Attrs to support all version 17.4 through 19.x
- Adds Tox+Docker to better test multiple combinations locally
- Drops support for Python 3.4
=> [MINOR] Bump Attrs, drop Py3.4 support, add Tox+Docker for local tests

.gitignore, conformity/error.py, conformity/fields/basic.py, conformity/fields/country.py, conformity/fields/currency.py, conformity/fields/email.py, conformity/fields/meta.py, conformity/fields/structures.py, conformity/fields/temporal.py, conformity/utils.py, conformity/validator.py, setup.cfg, tests/test_fields.py, tests/test_fields_country.py, tests/test_fields_currency.py, tests/test_fields_email.py, tests/test_fields_meta.py, tests/test_utils.py, tests/test_validator.py
- Add exhaustive validation to all Conformity field arguments to avoid weird errors at runtime when Conformity fields are used incorrectly.
- Add Python type hints throughout the Conformity API to make using Conformity fields easier with type-smart IDEs.
- Write a bunch more tests to increase code coverage from 92% to 99%.
- Standardize on `.format` instead of `%` (previously this was inconsistent).
- Refactor `Dictionary` to be an `attr.s` class now (fully backwards-compatible, all features still work).
=> [MINOR] Support eager argument validation and type hints

conformity/validator.py, tests/test_validator.py
When a function is decorated with `validate_call` (or a method with `validate_method`), that resulting callable will include three new attributes that expose the callable's schema for purposes of introspection and propagation:
- `__validated_schema_args__`
- `__validated_schema_kwargs__`
- `__validated_schema_returns__`
=> [PATCH] Make validated functions and methods introspectable

conformity/fields/structures.py, tests/test_fields.py
When `Dictionary` is subclassed, the subclass should be able to specify empty `contents` and `optional_keys`. Additionally, subclassed `contents`, `allow_extra_keys`, and `description`, if specified, should be validated to be the proper type.
=> [PATCH] Regression: Fix Dictionary subclass processing and validation

conformity/fields/__init__.py, conformity/fields/meta.py, tests/test_fields_meta.py
Add a new `PythonPath` field to support checking the importability (and schema) of any Python item, and make it the superclass of `TypePath`.
=> [MINOR] Add PythonPath field, superclass of TypePath

conformity/fields/structures.py, conformity/settings/__init__.py, setup.py, tests/test_fields.py, tests/test_settings.py
This commit implements #65. PySOA's `Settings` are being used for many things beyond just PySOA - several other projects not otherwise using PySOA are importing PySOA just to use its `Settings` feature. Based on this use case, `Settings` is an appropriate member of the Conformity domain, so this is the Conformity commit to migrate `Settings` from PySOA to Conformity. There will be a corresponding PySOA commit to adopt this new Conformity feature.
=> [MINOR] Implement #65: Add support for generic Settings objects

conformity/fields/basic.py, conformity/fields/country.py, conformity/fields/currency.py, conformity/fields/email.py, conformity/fields/geo.py, conformity/fields/meta.py, conformity/fields/net.py, conformity/fields/structures.py, conformity/fields/temporal.py, conformity/utils.py, tests/test_fields.py, tests/test_settings.py
This commit fixes bug #68 (introspection in `Constant` was broken when its values had multiple types) and also adds missing typing information (0a5f13fa025f4af91f32b2a336218998d83b1e08 was apparently incomplete) to track down and fix other bugs in introspection in `Constant` and 2-3 other fields.
=> [MINOR] Fix #68 and find and fix other issues with typing

conformity/fields/currency.py, conformity/fields/email.py, conformity/fields/temporal.py, conformity/sphinx_ext/autodoc.py, docs/fields.rst, tests/sphinx_ext/test_autodoc.py, tests/test_fields.py, tests/test_fields_currency.py, tests/test_fields_email.py
- Rename `AmountDictionary` to `AmountRequestDictionary`
- Deprecate `AmountDictionary`
- Deprecated `*args` and `**kwargs` to `AmountRequestDictionary`
- Add `AmountResponseDictionary`
- Add `AmountString`
- Add a couple warnings for a few already-deprecated arguments
- Update tests
- Update documentation
=> [MINOR] Fix #71: Refactor the fields supporting Currint amounts

conformity/fields/__init__.py, conformity/fields/logging.py, conformity/fields/structures.py, conformity/sphinx_ext/autodoc.py, conformity/sphinx_ext/linkcode.py, docs/fields.rst, docs/reference.rst, docs/sphinx.rst, tests/sphinx_ext/test_autodoc.py, tests/test_fields.py, tests/test_logging.py
- Add standard Python logging config dict schema validation.
- Add support for a `Sequence` type (to support the above).
- Add support for extra validation for all collection (structure) types (to support the above).
- Fix a new bug in autodoc generation (to support the above).
- Update documentation (to support the above).
=> [MINOR] Add Python logging configuration validation schema

conformity/fields/logging.py, conformity/sphinx_ext/autodoc.py, tests/sphinx_ext/test_autodoc.py, tests/sphinx_ext/utils.py
If a method was decoratod, the annotations found for it by the Sphix extension did not match, and often resulted in errors. This fixes that bug.
=> [PATCH] Fix bug in Sphix ext improperly resolving signatures

conformity/sphinx_ext/autodoc.py, conformity/sphinx_ext/linkcode.py, tests/sphinx_ext/test_autodoc.py
In the Sphinx Autodoc and LinkCode extensions, if `inspect` cannot get the source lines for a member, that by extension means the member doesn't have annotations, so there's no reason to fail hard in `get_annotations`, and there's also no reason to fail hard in generating a link to the source code.
Also, add missing newline in settings schema documentation.
=> [PATCH] [SPHINX] Soft fail getting annotations when source not found

conformity/fields/basic.py, tests/test_fields.py
Currently, the `Constant` field raises an error when receiving and
trying to validate an unhashable value.
The reason is that `if value not in self.values:` expects a hashable
value, and fails with an error like `TypeError: unhashable type: 'list'`
otherwise.
=> [PATCH] Fix Constant field when receiving unhashable values

conformity/sphinx_ext/autodoc.py
Current issues reported by MyPy are:
```
conformity/sphinx_ext/autodoc.py:555: error: Value of type "Optional[Tuple[Any, ...]]" is not indexable
conformity/sphinx_ext/autodoc.py:570: error: Value of type "Optional[Dict[str, Any]]" is not indexable
Found 2 errors in 1 file (checked 40 source files)
```
=> [PATCH] Fix typing issues introduced with MyPy 0.750

conformity/fields/currency.py, docs/fields.rst, tests/test_fields_currency.py
Add a new field to validate currency codes. This field is a special extension of
Constant that ensures the value is a Unicode string that enforces the value meets the currency format as `'USD'`. It has one
argument, `code_filter`, which if specified must be a `typing.Callable[[typing.AnyStr], bool]`.
=> [MINOR] Add currency code field

conformity/fields/meta.py, setup.cfg, tests/test_fields_meta.py
The issue eventbrite/pymetrics#9 is caused by the fact that Conformity wraps `ImportError`s that occur during validation. This tiny tweak makes it possible for PyMetrics to easily detect such errors and include them in its circular-import protection code.
=> [PATCH] Differentiate import errors from other validation errors

conformity/fields/net.py
add explicit introspect type to IPAddress field type
we are using introspect types to get Conformity Fields. IPAddress introspect_type is "any" as it is not defined as an explicit type
=> Add introspect type to IPAddress
